studybud/base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('',views.getRoutes),
path('rooms/',views.getRooms),
path('room/<str:pk>',views.getRoom)

]
  

studybud/base/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

urlpatterns = [
    path('',views.home,name="home"),
    path('room/<str:pk>',views.room,name="room"),
    path('profile/<str:pk>',views.profile,name="user-profile"),
    
    path('create_room/',views.create_room,name="new_room"),
    path('update_room/<str:pk>',views.update_room,name="update_room"),
    path('delete_room/<str:pk>',views.delete_room,name="delete_room"),
    
    path('delete_msg/<str:pk>',views.delete_msg,name="delete_msg"),
    
    path('update_user/',views.update_user,name="update_user"),
    
    
    path('login/',views.login_page,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('register/',views.registerUser,name="register"),
    
    path('topic_page/',views.topic_page,name="topics"),
    path('activity_page/',views.activity,name="activity")
]

studybud/studybud/urls.py
from django.contrib import admin
from django.urls import path,include
from django.http import HttpResponse



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('api/',include('base.api.urls'))
]

studybud/base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Topic(models.Model):
    name=models.CharField(max_length=200)
    
    def __str__(self):#this will be displayed in the admin console
         return self.name

class project(models.Model):
    host=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    topic=models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    name=models.CharField(max_length=200)
    description=models.TextField(null=True,blank=True)
    participants=models.ManyToManyField(User,related_name='participants',blank=True)
    update=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    
    def __str__(self) :#this will be displayed in the admin console
        return self.name
    
class Message(models.Model):
        Project=models.ForeignKey(project,on_delete=models.CASCADE)
        user=models.ForeignKey(User,on_delete=models.CASCADE)
        body=models.TextField()
        update=models.DateTimeField(auto_now=True)
        created=models.DateTimeField(auto_now_add=True)
        
        
        
        def __str__(self):#this will be displayed in the admin console
             return self.body[:50]

studybud/base/forms.py
from django.forms import ModelForm
from .models import project
from django.contrib.auth.models import User

class Project_form(ModelForm):
    class Meta:
        
        fields='__all__'
        model=project
        exclude=['host','participants']

class UserForm(ModelForm):
    class Meta:
        model=User
        fields=['username','email']
        
        
        

        

studybud/base/api/views.py
from django.http import HttpResponse,JsonResponse
from django.shortcuts import render,redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response

from.serialization import RoomSerilizer
from base.models import project

routes=['GET routes/','GET api/rooms','GET api/room/<pk:id>']
rot='hello'

@api_view(['GET'])
def getRoutes(request):
    return Response(routes)

@api_view(['GET'])
def getRooms(request):
    room=project.objects.all()
    Roomserial=RoomSerilizer(room,many=True)
    print(Roomserial)
    return Response(Roomserial.data)
    
@api_view(['GET'])
def getRoom(request,pk):
    room=project.objects.get(id=pk)
    Roomserial=RoomSerilizer(room,many=False)
    return Response(Roomserial.data)
    
    
       

studybud/base/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.db.models import Q
from django.contrib.auth.models import User 
from .models import project,Topic,Message
from .forms import Project_form,UserForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

rooms=[
    
    
    
        {'id':1,'name':'UNITY'},
        {'id':2,'name':'UNREAL'},
        {'id':3,'name':'MACHINE LEARNING'},
        {'id':4,'name':'DEEP SPACE NETWORK'},
    ]
r1=['GTA 5','Red dead Redemption ','bully','L.A.Noir','MidNight club']

def login_page(request):
    page='login'
    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method=='POST':
        username=request.POST.get('username').lower()
        password=request.POST.get('password')
        
        try:
            user=User.objects.get(username=username)
        except:
            messages.error(request,"User doesn't exists")
        user=authenticate(request,username=username,password=password)
        
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            messages.error(request,"Username or password is incorrect")
                    
                 
            
    context={'page':page}
    return render(request,'base/login.html',context=context)

def logoutUser(request):
    logout(request)
    return redirect('home')

def registerUser(request):
    page='register'
    form=UserCreationForm()
    
    #process the form
    if request.method=="POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)# data cleaning so it is not saved(committed)
            user.username=user.username.lower()
            user.save()
            #login the user now
            login(request,user)
            return redirect('home')
        else:
            messages.error(request,"An error has occured")
            
    
    return render(request,'base/login.html',{'form':form})    

# Create your views here.
def home(Request):
    q=Request.GET.get('q') if Request.GET.get('q')!= None else ''
    print(q)
    #rooms=project.objects.all()
    rooms=project.objects.filter(Q(topic__name__icontains=q)|
                                 Q(name__icontains=q)|
                                 Q(description__icontains=q))
    room_count=rooms.count()
    room_messages=Message.objects.filter(Q(Project__name__icontains=q))
    topics=Topic.objects.all()[0:4]
    print(topics)
    cdata={'rooms':rooms,'topics':topics,'room_count':room_count,'room_messages':room_messages}#key is used in the HTML "rooms"
    #cdata1={'RockstarGames':r1}
    return render(Request,'base/home.html',cdata)

def room(request,pk):
    '''room_name=None
    for i in rooms:
        if i['id']==int(pk):
            room_name=i
    #form a context and send it 
    cdata={'room':room_name}    '''
    room_name=project.objects.get(id=pk)
    room_messages=room_name.message_set.all().order_by("-created") # type: ignore
    participants=room_name.participants.all()
    
    if request.method=="POST":
        msg=Message.objects.create(
            user=request.user,
            Project=room_name,
            body=request.POST.get('body')
        )
        room_name.participants.add(request.user)
        #room_name.save()
        return redirect('room',pk=room_name.id)
    
    cdata={'room':room_name,'room_messages':room_messages,'participants':participants}
    
    return render(request,'base/room.html',cdata)
 
def profile(request,pk):
    user=User.objects.get(id=pk)
    rooms=project.objects.filter(host=user)
    room_messages=user.message_set.all()
    topics=Topic.objects.all()
    print(rooms)
    context={'user':user,'rooms':rooms,'room_messages':room_messages,'topics':topics}
    return render(request,'base/profile.html',context)

@login_required(login_url='login')
def create_room(request):
    form=Project_form()
    topics=Topic.objects.all()
    if request.method=='POST':
        #get the topic
        topic_name=request.POST.get('topic')
        topic,created=Topic.objects.get_or_create(name=topic_name)
        project.objects.create(
            host=request.user,
            topic=topic,
            description=request.POST.get('description'),
            name=request.POST.get('name')
        )
        
        '''form1=Project_form(request.POST)#adds new room
        if form1.is_valid:
            room=form1.save(commit=False)#this gives the instance of the class
            room.host=request.user #setting up the host name 
            room.save()'''
        return redirect('home')
        
    cdata={'form':form,'topics':topics}
    return render(request,'base/room_form.html',cdata)

@login_required(login_url='login')
def update_room(request,pk):#to know what room we are updating 
        room=project.objects.get(id=pk)
        forms=Project_form(instance=room)
        topics=Topic.objects.all()
        
        #only the creator of the room should be able to modify
        if request.user!=room.host:
            return HttpResponse('Restricted!!')
        
        
        if request.method=='POST':
            #form=Project_form(request.POST,instance=room)#instance will replace the existing room
            #if form.is_valid:
            #    form.save()
            topic_name=request.POST.get('topic')
            topic,created=Topic.objects.get_or_create(name=topic_name)
            
            room.name=request.POST.get('name')
            room.description=request.POST.get('description')
            room.topic=topic
            room.save()
            
            return redirect('home')
        cdata={'form':forms,'topics':topics,'room':room}
        return render(request,'base/room_form.html',cdata)
    
@login_required(login_url='login')    
def delete_room(request,pk):
    room=project.objects.get(id=pk)
    
    #only the creator of the room should be able to modify
    if request.user!=room.host:
            return HttpResponse('Restricted!!')
    
    if request.method=='POST':
        room.delete()
        return redirect('home')
    return render(request,'base/confirmDelete.html',{'rooms':room})        

@login_required(login_url='login')    
def delete_msg(request,pk):
    msg=Message.objects.get(id=pk)
    
    #only the creator of the room should be able to modify
    if request.user!=msg.user:
            return HttpResponse('Restricted!!')
    
    if request.method=='POST':
        msg.delete()
        return redirect('home')
    return render(request,'base/confirmDelete.html',{'rooms':msg})    

@login_required(login_url='login')    
def update_user(request):
    user=request.user
    form=UserForm(instance=user)
    
    if request.method=='POST':
        form=UserForm(request.POST,instance=user)
        if form.is_valid:
            form.save()
            return redirect('user-profile',pk=user.id)
    
    return render(request,'base/update-user.html',{'form':form})

def topic_page(request):
    q=request.GET.get('q') if request.GET.get('q')!= None else ''
    topics=Topic.objects.filter(Q(name__icontains=q))
    
    return render(request,"base/topics.html",{'topics':topics})

def activity(request):
    
    room_messages=Message.objects.all()
    
    
    return render(request,"base/activity.html",{'room_messages':room_messages})

studybud/base/templates/base/activity.html
{% extends 'main.html' %}

{% block content %}
<main class="layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
              </path>
            </svg>
          </a>
          <h3>Recent Activities</h3>
        </div>
      </div>

      <div class="activities-page layout__body">

        {% for message in room_messages %}
        <div class="activities__box">
          <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
              <div class="avatar avatar--small">
                <img src="{{message.user.avatar.url}}" />
              </div>
              <p>
                @{{message.user}}
                <span>{{message.created|timesince}} ago</span>
              </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
              <a href="{% url 'delete-message' message.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                  </path>
                </svg>
              </a>
            </div>
            {% endif %}

          </div>
          <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'room' message.Project.id %}">{{message.Project}}</a>”</p>
            <div class="activities__boxRoomContent">
              {{message.body}}
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>
</main>
{% endblock content %}

studybud/base/templates/base/activity_component.html
<div class="activities">
  <div class="activities__header">
    <h2>Recent Activities</h2>
  </div>
  {% for msg in room_messages %}
  <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a href="{% url 'user-profile' msg.user.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="https://randomuser.me/api/portraits/women/11.jpg" alt="User avatar" />
        </div>
        <p>
          {{ msg.user }}
          <span>{{ msg.created|timesince }} ago</span>
        </p>
      </a>
      {% if request.user == msg.user %}
      <div class="roomListRoom__actions">
        <a href="{% url 'delete_msg' msg.id %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>remove</title>
            <path
              d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
          </svg>
        </a>
      </div>
      {% endif %}
    </div>
    <div class="activities__boxContent">
      <p>replied to post "<a href="{% url 'room' msg.Project.id %}">{{msg.Project}}</a>"</p>
      <div class="activities__boxRoomContent">
        {{msg}}
      </div>
    </div>
  </div>
  {% endfor %}
</div>









<!--<h3>Recent Activity</h3>
        <hr>
        {% for msg in room_messages %}
        <div>
            <small><a href= {% url 'user-profile' msg.user.id %} >@{{ msg.user }}</a>, {{ msg.created|timesince }} ago</small>
            <small>replied to "{{msg.Project}}"</small>
            <p>{{ msg }}</p>
            {% if request.user == msg.user %}
            <a href="{% url 'delete_msg' msg.id %}">delete</a>
            {% endif %}
        {% endfor %}-->

studybud/base/templates/base/confirmDelete.html
{% extends 'main.html' %}{%block content%}

<form method="POST" action="">
  {%csrf_token%}
  <p>do wanna delete this room {{rooms}}</p>
  <a href="{{request.META.HTTP_REFERER}}">GO BACK</a>
  <input type="submit" value="CONFIRM" />
  <form>{%endblock%}</form>
</form>

studybud/base/templates/base/feed.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
      <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="https://randomuser.me/api/portraits/women/11.jpg" />
        </div>
        <span>@{{room.host.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{room.created|timesince}} ago</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <a href="{% url 'room' room.id %}">{{ room.name }}</a>
      <p>
        {{room.description}}
      </p>
    </div>
    <div class="roomListRoom__meta">
      <a href="room.html" class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>user-group</title>
          <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
          ></path>
          <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
          ></path>
          <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
          ></path>
          <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
          ></path>
        </svg>
         {{room.participants.all.count}}  Joined
      </a>
      <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
  </div>
  {% endfor %} 











        

studybud/base/templates/base/home.html
{% extends "main.html" %}

{% block content %}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
        {% include "base/topics_component.html" %}
        
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search" action="{% url 'home' %}" method="GET">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts" name="q"/>
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>ACTIVE ROOMS: {{room_count}}</p>
            </div>
            <a class="btn btn--main" href="{% url 'new_room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>
          {% include "base/feed.html" %}
      
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
         {% include "base/activity_component.html" %}
        
        <!-- Activities End -->
      </div>
    </main>
    

  
{% endblock   %} 

studybud/base/templates/base/home_.html
{% extends 'main.html' %}

{% block content %}

<main class="layout layout--3">
  <div class="container">

    <!-- Topics Start -->
    {% include 'base/topics_component.html' %}

    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'home' %}" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Study Rooms</h2>
          <p>{{room_count}} Rooms available</p>
        </div>

        <a class="btn btn--main" href="{% url 'create-room' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z">
            </path>
          </svg>
          Create Room
        </a>
      </div>

      {% include 'base/feed_component.html' %}

    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activity_component.html' %}

    <!-- Activities End -->
  </div>
</main>

{% endblock %}

studybud/base/templates/base/homeold.html
{% extends 'main.html' %}
{% block content %}
<style>
    .home-container {
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
        gap: 2rem;
        padding: 2rem;
    }
    .topic-list, .room-list, .activity-list {
        background-color: #f8f9fa;
        border-radius: 8px;
        padding: 1rem;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .room-item {
        background-color: white;
        border-radius: 4px;
        padding: 1rem;
        margin-bottom: 1rem;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .room-actions {
        margin-bottom: 0.5rem;
    }
    .room-actions a {
        margin-right: 0.5rem;
        text-decoration: none;
        color: #007bff;
    }
    h1, h3, h5 {
        color: #333;
    }
    a {
        color: #007bff;
        text-decoration: none;
    }
    a:hover {
        text-decoration: underline;
    }
    .create-room-btn {
        display: inline-block;
        background-color: #28a745;
        color: white;
        padding: 0.5rem 1rem;
        border-radius: 4px;
        margin-bottom: 1rem;
    }
    .create-room-btn:hover {
        background-color: #218838;
        text-decoration: none;
    }
</style>
<div class="home-container">
    <div class="topic-list">
        {% include "base/topics.html" %}
    </div>

    <div class="room-list">
        <h1>Welcome to HOME</h1>
        <h5>{{ room_count }} Rooms Available</h5>
        <a href="{% url 'new_room' %}" class="create-room-btn">Create Room</a>
        {% include "base/feed.html" %}
    </div>

    <div class="activity-list">
        {% include "base/activity_component.html" %} 
        </div>
        
    </div>
</div>
{% endblock content %}

studybud/base/templates/base/login_old.html
{% extends 'main.html'  %}

{% block content %}

{% if page == "login" %}
<div>

    <form method="POST" action="">
        {% csrf_token %}
        <label>Username :</label> 
        <input type='text' name='username' placeholder='username'/>
        <label>password :</label> 
        <input type='password' name='password' placeholder='password'/>
        <input type ='submit' value='login'>

    </form>
    <p>New user?</p>
    <a href="{%url 'register'%}">Register</a>

</div>
{% else %}
<div>

    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type ='submit' value='Register'>

    </form>
    <p>Already an user?</p>
    <a href="{%url 'login'%}">login</a>

</div>
{% endif %}
{% endblock content%}

studybud/base/templates/base/profile_old.html
{% extends 'main.html' %}

{% block content %}
<style>
    .profile-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;

    }
</style>
<h1>{{user.username}}</h1>

<div class="profile-container">

<div>
{% include "base/topics.html" %}
</div>

<div>
     {% include "base/feed.html" %} 

</div>

<div>
{% include "base/activity_component.html" %}
</div>


</div>

{% endblock content %} 

studybud/base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form action="" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for topics" />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'topics' %}" class="active">All <span>{{topics.count}}</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="{% url 'home' %}?q={{topic.name}}">{{ topic.name }} <span>{{topic.project_set.all.count}}</span></a>
          </li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

studybud/base/templates/base/topics_component.html
<div class="topics">
    <div class="topics__header">
      <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'home' %}" class="active">All <span>{{room_count}}</span></a>
      </li>
      {% for topic in topics %}
      <li>
        <a href="{% url 'home' %}?q={{ topic.name }}">{{ topic.name }} <span>{{ topic.project_set.all.count }}</span></a>
      </li>
      {% endfor %}
    
    </ul>
    <a class="btn btn--link" href="{% url "topics" %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>
        